export type FarShape = 'hills' | 'peaks' | 'dunes' | 'sea' | 'volcano' | 'cave' | 'flat'

export type Decor =
  | 'grass'
  | 'trees'
  | 'pines'
  | 'palms'
  | 'cacti'
  | 'flowers'
  | 'stars'
  | 'waves'
  | 'lava'
  | 'embers'
  | 'snow'
  | 'caps'
  | 'aurora'
  | 'crystals'
  | 'stalactites'
  | 'lightning'
  | 'rain'
  | 'nebula'
  | 'fireflies'
  | 'leaves'
  | 'petals'
  | 'mist'
  | 'wisps'
  | 'tombstones'
  | 'skyline'
  | 'rainbow'
  | 'reeds'

export interface SceneTheme {
  label: string
  skyTop: string
  skyMid: string
  skyBottom: string
  sun: string
  sunEdge: string
  glow: string
  cloud: string
  cloudEdge: string
  cloudShade: string
  farHill: string
  farHillEdge: string
  nearHill: string
  nearHillEdge: string
  meadow: string
  meadowEdge: string
  tuft: string
  leaf: string
  leafEdge: string
  accent: string // lava, crystals, aurora, nebula
  accent2: string
  far: FarShape
  celestial: 'sun' | 'moon' | 'none'
  clouds: boolean
  decor: Decor[]
}

export const SCENE_THEMES = {
  meadow: {
    label: 'Meadow',
    skyTop: '#6fc6fb',
    skyMid: '#b8e6ff',
    skyBottom: '#eafaff',
    sun: '#ffe27a',
    sunEdge: '#f5b942',
    glow: '#fff3b0',
    cloud: '#ffffff',
    cloudEdge: '#a9d4f2',
    cloudShade: '#e4f3fd',
    farHill: '#b8e79c',
    farHillEdge: '#8acb6c',
    nearHill: '#98da74',
    nearHillEdge: '#6db552',
    meadow: '#7fcd5c',
    meadowEdge: '#5ca842',
    tuft: '#5fb547',
    leaf: '#78c95c',
    leafEdge: '#56a83f',
    accent: '#ff8fb1',
    accent2: '#ffd84d',
    far: 'hills',
    celestial: 'sun',
    clouds: true,
    decor: ['trees', 'grass', 'flowers']
  },
  forest: {
    label: 'Forest',
    skyTop: '#9fd6a0',
    skyMid: '#c9ebc8',
    skyBottom: '#eef9e6',
    sun: '#fff2a8',
    sunEdge: '#e8c75a',
    glow: '#fffbc8',
    cloud: '#f4fff0',
    cloudEdge: '#b6dcb2',
    cloudShade: '#dff1da',
    farHill: '#5aa468',
    farHillEdge: '#3f8650',
    nearHill: '#3f8a4d',
    nearHillEdge: '#2e6e3a',
    meadow: '#2f7a42',
    meadowEdge: '#235f32',
    tuft: '#27663a',
    leaf: '#2f8f4e',
    leafEdge: '#1f6a38',
    accent: '#fff27a',
    accent2: '#c8ff9a',
    far: 'hills',
    celestial: 'sun',
    clouds: true,
    decor: ['pines', 'grass', 'fireflies']
  },
  ocean: {
    label: 'Ocean',
    skyTop: '#4aa8e8',
    skyMid: '#9ad7f7',
    skyBottom: '#e4f6ff',
    sun: '#fff0a0',
    sunEdge: '#f5b942',
    glow: '#fff7c0',
    cloud: '#ffffff',
    cloudEdge: '#a9d4f2',
    cloudShade: '#e4f3fd',
    farHill: '#3d9ad6',
    farHillEdge: '#2a7fb8',
    nearHill: '#2f88c6',
    nearHillEdge: '#1f6fa8',
    meadow: '#5cc0e8',
    meadowEdge: '#3da4cf',
    tuft: '#8fdcf2',
    leaf: '#78c95c',
    leafEdge: '#56a83f',
    accent: '#ffffff',
    accent2: '#bfeaff',
    far: 'sea',
    celestial: 'sun',
    clouds: true,
    decor: ['waves']
  },
  beach: {
    label: 'Beach',
    skyTop: '#ffb27d',
    skyMid: '#ffd9b8',
    skyBottom: '#fff3e2',
    sun: '#fff0a0',
    sunEdge: '#f5a742',
    glow: '#fff3b0',
    cloud: '#ffffff',
    cloudEdge: '#f3cdb0',
    cloudShade: '#fde8d6',
    farHill: '#7fd0e8',
    farHillEdge: '#4fb2d1',
    nearHill: '#f7e2b5',
    nearHillEdge: '#e0c07a',
    meadow: '#efd39a',
    meadowEdge: '#d6b270',
    tuft: '#d9b872',
    leaf: '#4fb560',
    leafEdge: '#2f8f45',
    accent: '#ffffff',
    accent2: '#bfeaff',
    far: 'sea',
    celestial: 'sun',
    clouds: true,
    decor: ['palms', 'grass']
  },
  volcano: {
    label: 'Volcano',
    skyTop: '#2c1118',
    skyMid: '#8a2f22',
    skyBottom: '#f08a3c',
    sun: '#ffb347',
    sunEdge: '#ff7a1a',
    glow: '#ff9a3c',
    cloud: '#5a4a4a',
    cloudEdge: '#3a2c2c',
    cloudShade: '#4a3a3a',
    farHill: '#4a2c2c',
    farHillEdge: '#2e1a1a',
    nearHill: '#5c3a32',
    nearHillEdge: '#3d2520',
    meadow: '#3b2a2a',
    meadowEdge: '#261a1a',
    tuft: '#2a1c1c',
    leaf: '#4a2c2c',
    leafEdge: '#2e1a1a',
    accent: '#ff6a1a',
    accent2: '#ffc23c',
    far: 'volcano',
    celestial: 'none',
    clouds: true,
    decor: ['lava', 'embers']
  },
  glacier: {
    label: 'Glacier',
    skyTop: '#0d2a4a',
    skyMid: '#1d5a7a',
    skyBottom: '#6fb8c8',
    sun: '#f4f9ff',
    sunEdge: '#cfe3f2',
    glow: '#cfe9ff',
    cloud: '#cfe3f2',
    cloudEdge: '#9cc4de',
    cloudShade: '#b8d4e8',
    farHill: '#bcd8ec',
    farHillEdge: '#8fb8d4',
    nearHill: '#e2f0f8',
    nearHillEdge: '#b5d2e4',
    meadow: '#f5fbff',
    meadowEdge: '#c5deec',
    tuft: '#d4e8f4',
    leaf: '#bcd8ec',
    leafEdge: '#8fb8d4',
    accent: '#5affc0',
    accent2: '#a07aff',
    far: 'peaks',
    celestial: 'moon',
    clouds: false,
    decor: ['stars', 'aurora', 'caps', 'snow']
  },
  desert: {
    label: 'Desert',
    skyTop: '#6ec0ee',
    skyMid: '#bfe3f5',
    skyBottom: '#fff0c8',
    sun: '#fff1a0',
    sunEdge: '#f5b030',
    glow: '#fff0a8',
    cloud: '#ffffff',
    cloudEdge: '#cde6f2',
    cloudShade: '#eef6f9',
    farHill: '#f2c777',
    farHillEdge: '#d9a655',
    nearHill: '#e9b862',
    nearHillEdge: '#c9953f',
    meadow: '#dba653',
    meadowEdge: '#b98532',
    tuft: '#b98532',
    leaf: '#5aa65a',
    leafEdge: '#3f8040',
    accent: '#ff8fb1',
    accent2: '#ffd84d',
    far: 'dunes',
    celestial: 'sun',
    clouds: true,
    decor: ['cacti']
  },
  mountain: {
    label: 'Mountain',
    skyTop: '#7fb2e0',
    skyMid: '#bcd8f0',
    skyBottom: '#e8f1f8',
    sun: '#fff2b0',
    sunEdge: '#f0c860',
    glow: '#fff7d0',
    cloud: '#ffffff',
    cloudEdge: '#b6cfe4',
    cloudShade: '#e6eef5',
    farHill: '#8f9aa8',
    farHillEdge: '#6a7482',
    nearHill: '#6f7d6a',
    nearHillEdge: '#55634f',
    meadow: '#5f7a55',
    meadowEdge: '#486042',
    tuft: '#4a6444',
    leaf: '#3f7a4a',
    leafEdge: '#2c5a36',
    accent: '#ffffff',
    accent2: '#ffffff',
    far: 'peaks',
    celestial: 'sun',
    clouds: true,
    decor: ['caps', 'pines', 'grass']
  },
  cave: {
    label: 'Cave',
    skyTop: '#15121f',
    skyMid: '#251c33',
    skyBottom: '#3a2c4c',
    sun: '#fff',
    sunEdge: '#fff',
    glow: '#fff',
    cloud: '#fff',
    cloudEdge: '#fff',
    cloudShade: '#fff',
    farHill: '#3b2f4a',
    farHillEdge: '#2a2036',
    nearHill: '#4a3a5c',
    nearHillEdge: '#352944',
    meadow: '#2f2640',
    meadowEdge: '#221a30',
    tuft: '#241c33',
    leaf: '#3b2f4a',
    leafEdge: '#2a2036',
    accent: '#5ad8ff',
    accent2: '#ff7ad8',
    far: 'cave',
    celestial: 'none',
    clouds: false,
    decor: ['stalactites', 'crystals']
  },
  storm: {
    label: 'Storm',
    skyTop: '#232b36',
    skyMid: '#465263',
    skyBottom: '#7a8797',
    sun: '#fff',
    sunEdge: '#fff',
    glow: '#fff',
    cloud: '#5a6573',
    cloudEdge: '#3d4652',
    cloudShade: '#4a5360',
    farHill: '#4b6b5a',
    farHillEdge: '#37504a',
    nearHill: '#3f5e4d',
    nearHillEdge: '#2e4a3c',
    meadow: '#355443',
    meadowEdge: '#264033',
    tuft: '#2a4638',
    leaf: '#3f6b50',
    leafEdge: '#2a4a38',
    accent: '#fff6a8',
    accent2: '#cfe0f0',
    far: 'hills',
    celestial: 'none',
    clouds: true,
    decor: ['grass', 'rain', 'lightning']
  },
  cosmic: {
    label: 'Cosmic',
    skyTop: '#0b0620',
    skyMid: '#2a1058',
    skyBottom: '#5b2a8c',
    sun: '#e8d8ff',
    sunEdge: '#b79cf0',
    glow: '#c8a8ff',
    cloud: '#fff',
    cloudEdge: '#fff',
    cloudShade: '#fff',
    farHill: '#3b2a6e',
    farHillEdge: '#2a1c52',
    nearHill: '#4a3590',
    nearHillEdge: '#33236e',
    meadow: '#352570',
    meadowEdge: '#261a55',
    tuft: '#2a1d5a',
    leaf: '#3b2a6e',
    leafEdge: '#2a1c52',
    accent: '#ff5ad0',
    accent2: '#5ad8ff',
    far: 'hills',
    celestial: 'moon',
    clouds: false,
    decor: ['nebula', 'stars', 'crystals']
  },
  sunset: {
    label: 'Sunset',
    skyTop: '#ff7b5c',
    skyMid: '#ffb88a',
    skyBottom: '#ffe3b8',
    sun: '#ffd36b',
    sunEdge: '#f59b3a',
    glow: '#ffb36b',
    cloud: '#ffd9c2',
    cloudEdge: '#f2a58a',
    cloudShade: '#f7b79d',
    farHill: '#b07a8f',
    farHillEdge: '#8f5d75',
    nearHill: '#c3b160',
    nearHillEdge: '#a39343',
    meadow: '#a8a24e',
    meadowEdge: '#8a8438',
    tuft: '#8e8a3c',
    leaf: '#8aa04f',
    leafEdge: '#6a8038',
    accent: '#ff8fb1',
    accent2: '#ffd84d',
    far: 'hills',
    celestial: 'sun',
    clouds: true,
    decor: ['trees', 'grass', 'flowers']
  },
  night: {
    label: 'Night',
    skyTop: '#1b1d4a',
    skyMid: '#2f3270',
    skyBottom: '#4b4f8c',
    sun: '#f4f1de',
    sunEdge: '#d8d2b0',
    glow: '#cfd3ff',
    cloud: '#6a6fae',
    cloudEdge: '#4b4f8c',
    cloudShade: '#565b9a',
    farHill: '#2f5d55',
    farHillEdge: '#244a43',
    nearHill: '#3f6b4f',
    nearHillEdge: '#2b5039',
    meadow: '#345a42',
    meadowEdge: '#264733',
    tuft: '#2c4f3a',
    leaf: '#2f7a55',
    leafEdge: '#1f5a3e',
    accent: '#ffe27a',
    accent2: '#c8ff9a',
    far: 'hills',
    celestial: 'moon',
    clouds: true,
    decor: ['trees', 'grass', 'stars', 'fireflies']
  },
  autumn: {
    label: 'Autumn',
    skyTop: '#f2a56a',
    skyMid: '#f9cfa0',
    skyBottom: '#fff0dc',
    sun: '#ffe0a0',
    sunEdge: '#f0a040',
    glow: '#ffd9a0',
    cloud: '#fff4e6',
    cloudEdge: '#f0c8a0',
    cloudShade: '#fbe3cc',
    farHill: '#e6a050',
    farHillEdge: '#c47a2a',
    nearHill: '#d98a3a',
    nearHillEdge: '#b06a22',
    meadow: '#c97a2c',
    meadowEdge: '#a35c18',
    tuft: '#a85a1a',
    leaf: '#e8731f',
    leafEdge: '#b84a0c',
    accent: '#ffb347',
    accent2: '#e8451f',
    far: 'hills',
    celestial: 'sun',
    clouds: true,
    decor: ['trees', 'grass', 'leaves']
  },
  blossom: {
    label: 'Blossom',
    skyTop: '#ffb8d8',
    skyMid: '#ffdcec',
    skyBottom: '#fff8fb',
    sun: '#fff3b0',
    sunEdge: '#f5c060',
    glow: '#fff0c8',
    cloud: '#ffffff',
    cloudEdge: '#f6c4da',
    cloudShade: '#fde6ef',
    farHill: '#f7c0d8',
    farHillEdge: '#e898b8',
    nearHill: '#a8e0a0',
    nearHillEdge: '#7cc078',
    meadow: '#8fd48a',
    meadowEdge: '#62b45e',
    tuft: '#6ab866',
    leaf: '#ff9ec4',
    leafEdge: '#e0709c',
    accent: '#ffb7d2',
    accent2: '#ffffff',
    far: 'hills',
    celestial: 'sun',
    clouds: true,
    decor: ['trees', 'grass', 'flowers', 'petals']
  },
  rainbow: {
    label: 'Rainbow',
    skyTop: '#6cc8ff',
    skyMid: '#bfe9ff',
    skyBottom: '#fffbe8',
    sun: '#fff6a8',
    sunEdge: '#f5c842',
    glow: '#fff7c0',
    cloud: '#ffffff',
    cloudEdge: '#a9d4f2',
    cloudShade: '#e4f3fd',
    farHill: '#c8f0b8',
    farHillEdge: '#98d888',
    nearHill: '#a8e898',
    nearHillEdge: '#78c868',
    meadow: '#8ade78',
    meadowEdge: '#5cbc50',
    tuft: '#4cb040',
    leaf: '#78c95c',
    leafEdge: '#56a83f',
    accent: '#ff8fb1',
    accent2: '#ffd84d',
    far: 'hills',
    celestial: 'sun',
    clouds: true,
    decor: ['rainbow', 'grass', 'flowers']
  },
  swamp: {
    label: 'Swamp',
    skyTop: '#5e7e50',
    skyMid: '#8fa880',
    skyBottom: '#c4d4b0',
    sun: '#fff',
    sunEdge: '#fff',
    glow: '#fff',
    cloud: '#a8b898',
    cloudEdge: '#7e9070',
    cloudShade: '#94a684',
    farHill: '#4a6a46',
    farHillEdge: '#385436',
    nearHill: '#3f5e3a',
    nearHillEdge: '#2e4a2c',
    meadow: '#4a5a30',
    meadowEdge: '#364320',
    tuft: '#2e4020',
    leaf: '#3e6a3a',
    leafEdge: '#2a4a28',
    accent: '#c8ff8a',
    accent2: '#8affc0',
    far: 'hills',
    celestial: 'none',
    clouds: true,
    decor: ['trees', 'reeds', 'mist', 'fireflies']
  },
  haunted: {
    label: 'Haunted',
    skyTop: '#100822',
    skyMid: '#2a1450',
    skyBottom: '#4a2a70',
    sun: '#ece4ff',
    sunEdge: '#b8a8e8',
    glow: '#c8b8ff',
    cloud: '#3a2a5a',
    cloudEdge: '#2a1c44',
    cloudShade: '#32244e',
    farHill: '#2a1c40',
    farHillEdge: '#1c1230',
    nearHill: '#34244e',
    nearHillEdge: '#241838',
    meadow: '#271b3a',
    meadowEdge: '#1a1228',
    tuft: '#1e1430',
    leaf: '#3a2a5a',
    leafEdge: '#2a1c44',
    accent: '#8affc8',
    accent2: '#c8a0ff',
    far: 'hills',
    celestial: 'moon',
    clouds: true,
    decor: ['stars', 'mist', 'tombstones', 'wisps']
  },
  city: {
    label: 'Neon City',
    skyTop: '#1a0b3a',
    skyMid: '#4a1a6a',
    skyBottom: '#ff6aa0',
    sun: '#ffe8f4',
    sunEdge: '#ff9ac8',
    glow: '#ff9ac8',
    cloud: '#fff',
    cloudEdge: '#fff',
    cloudShade: '#fff',
    farHill: '#150a2e',
    farHillEdge: '#2a1450',
    nearHill: '#1e1040',
    nearHillEdge: '#2f1a5c',
    meadow: '#241248',
    meadowEdge: '#34206a',
    tuft: '#241248',
    leaf: '#150a2e',
    leafEdge: '#2a1450',
    accent: '#3affe0',
    accent2: '#ff4ad0',
    far: 'flat',
    celestial: 'moon',
    clouds: false,
    decor: ['stars', 'skyline']
  }
} satisfies Record<string, SceneTheme>

export type BackgroundId = keyof typeof SCENE_THEMES

// Order shown in Settings: bright and natural first, then dark and dramatic
export const BACKGROUND_IDS: BackgroundId[] = [
  'meadow',
  'forest',
  'autumn',
  'blossom',
  'rainbow',
  'ocean',
  'beach',
  'desert',
  'sunset',
  'mountain',
  'glacier',
  'swamp',
  'night',
  'haunted',
  'city',
  'storm',
  'volcano',
  'cave',
  'cosmic'
]

// Small preview swatch derived from the theme's sky and ground colours
export function swatch(id: BackgroundId): string {
  const t: SceneTheme = SCENE_THEMES[id]
  return `linear-gradient(to bottom, ${t.skyTop} 0%, ${t.skyBottom} 55%, ${t.nearHill} 55%, ${t.meadow} 100%)`
}
